# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: macOS

on:
  push:
    branches-ignore:
    - deepsource-fix-**
    - renovate/**
    - weblate
  pull_request:

permissions:
  contents: read

jobs:
  macos:
    # This verifies that installation instructions works, any changes here
    # need to be reflected in docs/admin/install/venv-macos.rst
    runs-on: macos-13
    env:
      PYTHONUNBUFFERED: 1
      PYTHONWARNINGS: default,ignore:unclosed:ResourceWarning
    steps:
    - uses: actions/checkout@v4
    - run: brew update
    - name: Install Python
      run: brew link --overwrite python
    - name: Install brew dependencies
      run: brew install pango cairo gobject-introspection glib libyaml tvuotila/libxmlsec1/libxmlsec1@1.2.37 openssl pkg-config zstd xxhash
    - name: Install Weblate
      run: pip3 install -e .[all,test]
